version: '3.8'

services:
  app:
    build: .
    container_name: medmitra_app
    restart: always
    ports:
      - "80:3000" # Expose directly on HTTP Port 80
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=Asia/Kolkata
    deploy:
      resources:
        limits:
          memory: 400M